export const KENYAN_COUNTIES = [
  'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet',
  'Embu', 'Garissa', 'Homa Bay', 'Isiolo', 'Kajiado',
  'Kakamega', 'Kericho', 'Kiambu', 'Kilifi', 'Kirinyaga',
  'Kisii', 'Kisumu', 'Kitui', 'Kwale', 'Laikipia',
  'Lamu', 'Machakos', 'Makueni', 'Mandera', 'Marsabit',
  'Meru', 'Migori', 'Mombasa', 'Murang\'a', 'Nairobi',
  'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua',
  'Nyeri', 'Samburu', 'Siaya', 'Taita-Taveta', 'Tana River',
  'Tharaka-Nithi', 'Trans-Nzoia', 'Turkana', 'Uasin Gishu',
  'Vihiga', 'Wajir', 'West Pokot',
] as const;

export const EDUCATION_LEVELS = [
  'Primary',
  'Secondary (Form 1-4)',
  'KCSE Completed',
  'TVET Certificate',
  'TVET Diploma',
  'Undergraduate',
  'Postgraduate',
] as const;

export const CAREER_CATEGORIES = [
  'Agriculture & Food Security',
  'Technology & Digital Services',
  'Healthcare & Medical Services',
  'Education & Training',
  'Finance & Accounting',
  'Engineering & Infrastructure',
  'Tourism & Hospitality',
  'Media & Communications',
  'Environmental Conservation',
  'Manufacturing & Industry',
  'Government & Public Service',
  'Law & Legal Services',
  'Creative Arts & Design',
  'Renewable Energy',
  'Logistics & Supply Chain',
] as const;

export const SKILLS_LIST = [
  'Problem Solving', 'Critical Thinking', 'Communication', 'Teamwork',
  'Digital Literacy', 'Data Analysis', 'Project Management', 'Leadership',
  'Customer Service', 'Financial Management', 'Research', 'Writing',
  'Public Speaking', 'Coding', 'Graphic Design', 'Marketing',
  'Sales', 'Teaching', 'Nursing', 'Carpentry', 'Plumbing',
  'Electrical Work', 'Agriculture', 'Food Processing', 'Mechanical Repair',
  'Tailoring', 'Masonry', 'Welding', 'Hairdressing', 'Catering',
] as const;

export const LANGUAGE_PREFERENCES = ['en', 'sw'] as const;

export const ASSESSMENT_QUESTIONS = [
  {
    id: 'q1',
    question: 'What subjects do you enjoy the most in school?',
    type: 'multi_select' as const,
    options: ['Mathematics', 'Sciences', 'Languages', 'Humanities', 'Technical Subjects', 'Creative Arts', 'Business Studies'],
  },
  {
    id: 'q2',
    question: 'How do you prefer to solve problems?',
    type: 'single_select' as const,
    options: ['Analytical and systematic', 'Creative and innovative', 'Collaborative with others', 'Hands-on and practical', 'Research-based'],
  },
  {
    id: 'q3',
    question: 'Which work environment appeals to you most?',
    type: 'single_select' as const,
    options: ['Office setting', 'Outdoor/field work', 'Workshop/laboratory', 'Classroom/training', 'Healthcare facility', 'Creative studio'],
  },
  {
    id: 'q4',
    question: 'What type of impact do you want to make?',
    type: 'single_select' as const,
    options: ['Economic growth and business', 'Community development', 'Health and wellbeing', 'Environmental sustainability', 'Education and knowledge', 'Technology and innovation'],
  },
  {
    id: 'q5',
    question: 'How comfortable are you with technology?',
    type: 'scale' as const,
    min: 1,
    max: 5,
    labels: ['Not comfortable', 'Very comfortable'],
  },
  {
    id: 'q6',
    question: 'Which of these activities would you enjoy most?',
    type: 'multi_select' as const,
    options: ['Building or fixing things', 'Helping people solve problems', 'Creating art or content', 'Organizing events or teams', 'Studying and researching', 'Starting a business'],
  },
  {
    id: 'q7',
    question: 'What matters most to you in a career?',
    type: 'single_select' as const,
    options: ['Financial stability', 'Job security', 'Making a difference', 'Creative freedom', 'Continuous learning', 'Work-life balance'],
  },
  {
    id: 'q8',
    question: 'How do you handle challenges?',
    type: 'single_select' as const,
    options: ['I plan carefully before acting', 'I seek advice from others', 'I learn by trial and error', 'I research and analyze first', 'I take immediate action'],
  },
  {
    id: 'q9',
    question: 'Which Kenya Vision 2030 pillar interests you most?',
    type: 'single_select' as const,
    options: ['Economic Pillar (growth, agriculture, trade)', 'Social Pillar (health, education, housing)', 'Political Pillar (governance, democracy)'],
  },
  {
    id: 'q10',
    question: 'What is your strongest personal quality?',
    type: 'single_select' as const,
    options: ['Persistence', 'Creativity', 'Empathy', 'Analytical thinking', 'Adaptability', 'Leadership'],
  },
  {
    id: 'q11',
    question: 'How far are you willing to relocate for opportunities?',
    type: 'single_select' as const,
    options: ['Within my county only', 'Neighboring counties', 'Anywhere in Kenya', 'East Africa region', 'International opportunities'],
  },
  {
    id: 'q12',
    question: 'What is your preferred learning style?',
    type: 'single_select' as const,
    options: ['Reading and studying', 'Hands-on practice', 'Watching demonstrations', 'Group discussions', 'Online/self-paced'],
  },
  {
    id: 'q13',
    question: 'Which emerging field excites you the most?',
    type: 'multi_select' as const,
    options: ['Artificial Intelligence', 'Renewable Energy', 'AgriTech', 'FinTech', 'HealthTech', 'Creative Economy', 'Green Construction', 'Digital Media'],
  },
  {
    id: 'q14',
    question: 'How important is entrepreneurship to you?',
    type: 'scale' as const,
    min: 1,
    max: 5,
    labels: ['Prefer employment', 'Want my own business'],
  },
  {
    id: 'q15',
    question: 'What is your biggest constraint right now?',
    type: 'single_select' as const,
    options: ['Financial limitations', 'Lack of information/guidance', 'Limited educational options', 'Family responsibilities', 'Geographic isolation', 'No major constraints'],
  },
] as const;

export const SCHOLARSHIPS_SEED = [
  {
    name: 'HELB Loan - TVET',
    provider: 'Higher Education Loans Board',
    description: 'Government loan for TVET students across Kenya. Covers tuition and some living expenses.',
    eligibility: { education_levels: ['TVET Certificate', 'TVET Diploma'], counties: [], gender: 'all', financial_need: true },
    amount: 'KES 40,000 - 60,000/year',
    deadline: 'Rolling admissions',
    url: 'https://helb.co.ke',
  },
  {
    name: 'Masters Scholarship - DAAD',
    provider: 'German Academic Exchange Service',
    description: 'Full scholarship for Kenyan graduates to pursue Masters in Germany. Covers tuition, living, and travel.',
    eligibility: { education_levels: ['Undergraduate'], counties: [], gender: 'all', financial_need: true },
    amount: 'Full funding',
    deadline: 'Annual - October intake',
    url: 'https://daad.de',
  },
  {
    name: 'Equity Group Foundation Wings',
    provider: 'Equity Group Foundation',
    description: 'Wings to Fly scholarship for academically gifted but financially disadvantaged secondary school students.',
    eligibility: { education_levels: ['Secondary (Form 1-4)'], counties: [], gender: 'all', financial_need: true },
    amount: 'Full secondary education funding',
    deadline: 'Annual - January intake',
    url: 'https://equitygroupfoundation.com',
  },
  {
    name: 'KCB Foundation Scholarship',
    provider: 'KCB Foundation',
    description: 'Scholarship for bright but needy students. Covers secondary and university education.',
    eligibility: { education_levels: ['Secondary (Form 1-4)', 'KCSE Completed', 'Undergraduate'], counties: [], gender: 'all', financial_need: true },
    amount: 'Full funding',
    deadline: 'Annual - March',
    url: 'https://kcbgroup.com',
  },
  {
    name: 'M-Pesa Foundation Academy',
    provider: 'M-Pesa Foundation',
    description: 'Fully funded secondary education for talented students from disadvantaged backgrounds.',
    eligibility: { education_levels: ['Secondary (Form 1-4)'], counties: [], gender: 'all', financial_need: true },
    amount: 'Full boarding education',
    deadline: 'Annual - September',
    url: 'https://mpesafoundationacademy.ac.ke',
  },
  {
    name: 'Aga Khan Foundation Scholarship',
    provider: 'Aga Khan Foundation',
    description: 'International scholarship for postgraduate studies. 50% grant, 50% loan.',
    eligibility: { education_levels: ['Undergraduate', 'Postgraduate'], counties: [], gender: 'all', financial_need: true },
    amount: '50% grant + 50% loan',
    deadline: 'Annual - March',
    url: 'https://akdn.org',
  },
  {
    name: 'Women in Tech Africa Scholarship',
    provider: 'Women in Tech Africa',
    description: 'Scholarship for young women pursuing technology-related courses.',
    eligibility: { education_levels: ['KCSE Completed', 'TVET Certificate', 'TVET Diploma', 'Undergraduate'], counties: [], gender: 'female', financial_need: false },
    amount: 'KES 100,000 - 500,000',
    deadline: 'Annual - April',
    url: 'https://womenintechnafrica.com',
  },
  {
    name: 'KEF University Scholarship',
    provider: 'Kenya Education Fund',
    description: 'Supports needy students admitted to public universities in Kenya.',
    eligibility: { education_levels: ['KCSE Completed', 'Undergraduate'], counties: [], gender: 'all', financial_need: true },
    amount: 'KES 50,000 - 80,000/year',
    deadline: 'Annual - May',
    url: 'https://kenyaeducationfund.org',
  },
  {
    name: 'County Bursary Programs',
    provider: 'County Governments',
    description: 'Each county government offers bursaries for residents. Amounts and criteria vary by county.',
    eligibility: { education_levels: ['Secondary (Form 1-4)', 'TVET Certificate', 'TVET Diploma', 'Undergraduate'], counties: KENYAN_COUNTIES as unknown as string[], gender: 'all', financial_need: true },
    amount: 'KES 10,000 - 50,000/year',
    deadline: 'Varies by county',
    url: 'Contact your county office',
  },
  {
    name: 'USAID Kenya Scholarship',
    provider: 'USAID',
    description: 'Scholarship for students in arid and semi-arid lands (ASAL) counties pursuing higher education.',
    eligibility: { education_levels: ['KCSE Completed', 'Undergraduate'], counties: ['Garissa', 'Mandera', 'Wajir', 'Marsabit', 'Turkana', 'Samburu', 'Isiolo', 'Tana River', 'Lamu', 'Kwale', 'Kilifi', 'Taita-Taveta', 'West Pokot', 'Baringo'], gender: 'all', financial_need: true },
    amount: 'Full funding',
    deadline: 'Annual - February',
    url: 'https://usaid.gov/kenya',
  },
] as const;

export const TVET_PROGRAMS_SEED = [
  { name: 'Electrical Engineering', institution: 'Kenya Technical Training College', location: 'Nairobi', level: 'Diploma', duration: '3 years', career_paths: ['Electrical Engineer', 'Power Systems Technician', 'Renewable Energy Technician'] },
  { name: 'Information Technology', institution: 'Kabete Technical Institute', location: 'Nairobi', level: 'Certificate', duration: '2 years', career_paths: ['IT Support', 'Software Developer', 'Network Administrator'] },
  { name: 'Automotive Engineering', institution: 'Nairobi Technical Training Institute', location: 'Nairobi', level: 'Diploma', duration: '3 years', career_paths: ['Automotive Engineer', 'Vehicle Inspector', 'Workshop Manager'] },
  { name: 'Hospitality Management', institution: 'Utalii College', location: 'Nairobi', level: 'Diploma', duration: '2 years', career_paths: ['Hotel Manager', 'Chef', 'Tourism Officer'] },
  { name: 'Building Technology', institution: 'Nyeri Technical Training Institute', location: 'Nyeri', level: 'Diploma', duration: '3 years', career_paths: ['Site Engineer', 'Quantity Surveyor', 'Construction Manager'] },
  { name: 'Agricultural Engineering', institution: 'Egerton University TVET', location: 'Nakuru', level: 'Certificate', duration: '2 years', career_paths: ['Agricultural Officer', 'Farm Manager', 'AgriTech Specialist'] },
  { name: 'Medical Laboratory', institution: 'Kenya Medical Training College', location: 'Multiple Campuses', level: 'Diploma', duration: '3 years', career_paths: ['Lab Technician', 'Research Assistant', 'Quality Controller'] },
  { name: 'Fashion Design', institution: 'Bura Technical Training Institute', location: 'Taita-Taveta', level: 'Certificate', duration: '2 years', career_paths: ['Fashion Designer', 'Textile Technologist', 'Garment Production Manager'] },
  { name: 'Renewable Energy Technology', institution: 'Kiambu Institute of Science and Technology', location: 'Kiambu', level: 'Diploma', duration: '2 years', career_paths: ['Solar Technician', 'Energy Auditor', 'Green Energy Consultant'] },
  { name: 'Business Administration', institution: 'Mombasa Technical Training Institute', location: 'Mombasa', level: 'Diploma', duration: '2 years', career_paths: ['Business Manager', 'Entrepreneur', 'Operations Manager'] },
] as const;

export const EMERGING_CAREERS = [
  { title: 'AI/ML Engineer', sector: 'Technology', demand: 'Very High', avg_salary: 'KES 800K - 3M/year', required_education: 'Undergraduate + Certifications', growth: '35%' },
  { title: 'Solar Energy Technician', sector: 'Renewable Energy', demand: 'High', avg_salary: 'KES 300K - 800K/year', required_education: 'TVET Diploma', growth: '28%' },
  { title: 'AgriTech Specialist', sector: 'Agriculture & Technology', demand: 'High', avg_salary: 'KES 400K - 1.2M/year', required_education: 'TVET Diploma or Undergraduate', growth: '25%' },
  { title: 'Data Analyst', sector: 'Technology', demand: 'Very High', avg_salary: 'KES 500K - 2M/year', required_education: 'Undergraduate', growth: '30%' },
  { title: 'Cybersecurity Analyst', sector: 'Technology', demand: 'Very High', avg_salary: 'KES 600K - 2.5M/year', required_education: 'Undergraduate + Certifications', growth: '32%' },
  { title: 'Green Building Consultant', sector: 'Construction', demand: 'Medium', avg_salary: 'KES 400K - 1M/year', required_education: 'TVET Diploma or Undergraduate', growth: '20%' },
  { title: 'Digital Content Creator', sector: 'Creative Economy', demand: 'High', avg_salary: 'KES 200K - 1.5M/year', required_education: 'Certificate or Self-taught', growth: '22%' },
  { title: 'Health Informatics Officer', sector: 'Healthcare & Technology', demand: 'Medium-High', avg_salary: 'KES 500K - 1.5M/year', required_education: 'Undergraduate', growth: '18%' },
  { title: 'Supply Chain Analyst', sector: 'Logistics', demand: 'High', avg_salary: 'KES 400K - 1.2M/year', required_education: 'Undergraduate', growth: '15%' },
  { title: 'FinTech Developer', sector: 'Finance & Technology', demand: 'Very High', avg_salary: 'KES 700K - 2.5M/year', required_education: 'Undergraduate', growth: '33%' },
] as const;
