'use client';

import React, { useEffect, useState, useRef } from 'react';
import { useAuth } from '@/lib/auth-context';
import { useRouter } from 'next/navigation';
import { Navbar } from '@/components/layout/navbar';
import { Footer } from '@/components/layout/footer';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { FileText, Loader2, Download, CheckCircle2, Clock, Target } from 'lucide-react';
import type { PlanPhase } from '@/lib/types';

export default function ActionPlanPage() {
  const { user } = useAuth();
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [hasData, setHasData] = useState(false);
  const [plan30, setPlan30] = useState<PlanPhase | null>(null);
  const [plan90, setPlan90] = useState<PlanPhase | null>(null);
  const [plan1Year, setPlan1Year] = useState<PlanPhase | null>(null);
  const [reasoning, setReasoning] = useState('');
  const [approved, setApproved] = useState(true);
  const planRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!user) {
      router.push('/auth/signin');
    } else {
      fetchExistingPlan();
    }
  }, [user, router]);

  const fetchExistingPlan = async () => {
    if (!user) return;
    try {
      const res = await fetch(`/api/dashboard?user_id=${user!.id}`);
      const result = await res.json();
      if (result.data?.actionPlan) {
        const plan = result.data.actionPlan;
        setPlan30(plan.plan_30_days);
        setPlan90(plan.plan_90_days);
        setPlan1Year(plan.plan_1_year);
        setReasoning(plan.reasoning || '');
        setApproved(plan.guardian_approved);
        setHasData(true);
      }
    } catch {
      // silent
    }
  };

  const generatePlan = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const careerPath = 'Technology';
      const res = await fetch('/api/action-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: user.id, career_path: careerPath }),
      });
      const result = await res.json();
      if (result.error) throw new Error(result.error);
      if (result.data) {
        setPlan30(result.data.plan_30_days);
        setPlan90(result.data.plan_90_days);
        setPlan1Year(result.data.plan_1_year);
        setReasoning(result.data.reasoning || '');
        setApproved(result.data.guardian_approved);
        setHasData(true);
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to generate plan';
      alert(message);
    } finally {
      setLoading(false);
    }
  };

  const exportPDF = () => {
    if (!planRef.current) return;
    const content = planRef.current;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>NuruPath AI - Career Action Plan</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a; }
            h1 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 8px; }
            h2 { color: #15803d; margin-top: 24px; }
            h3 { color: #166534; }
            .phase { margin: 16px 0; padding: 12px; border: 1px solid #e5e7eb; border-radius: 8px; }
            .goals { list-style: disc; margin-left: 20px; }
            .action-item { margin: 8px 0; padding: 8px; background: #f0fdf4; border-radius: 4px; }
            .milestone { display: inline-block; margin: 4px; padding: 4px 12px; background: #dcfce7; border-radius: 12px; font-size: 14px; }
            .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; }
            .badge-green { background: #dcfce7; color: #166534; }
            .badge-gold { background: #fef9c3; color: #854d0e; }
            .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
          </style>
        </head>
        <body>
          ${content.innerHTML}
          <div class="footer">
            <p>Generated by NuruPath AI | ${new Date().toLocaleDateString()} | TRACK &amp; OASIS Compliant</p>
            <p>This plan was AI-generated and reviewed by a Guardian Agent. Please discuss with a career counselor.</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const renderPlanPhase = (plan: PlanPhase, color: 'green' | 'gold') => {
    const bgClass = color === 'green' ? 'bg-nuru-green-50 border-nuru-green-200' : 'bg-nuru-gold-50 border-nuru-gold-200';
    const badgeClass = color === 'green' ? 'bg-nuru-green-100 text-nuru-green-700' : 'bg-nuru-gold-100 text-nuru-gold-700';

    return (
      <div className="space-y-4">
        {plan.goals && plan.goals.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2">Goals</h3>
            <ul className="space-y-1">
              {plan.goals.map((goal, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  <Target className="h-4 w-4 text-nuru-green-600 mt-0.5 shrink-0" />
                  {goal}
                </li>
              ))}
            </ul>
          </div>
        )}

        {plan.actions && plan.actions.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2">Actions</h3>
            <div className="space-y-2">
              {plan.actions.map((action, i) => (
                <div key={i} className={`p-3 rounded-lg border ${bgClass}`}>
                  <div className="flex items-center justify-between mb-1">
                    <Badge className={badgeClass}>{action.week}</Badge>
                  </div>
                  <p className="text-sm font-medium">{action.task}</p>
                  <div className="flex items-center gap-4 mt-1 text-xs text-muted-foreground">
                    <span>Resource: {action.resource}</span>
                    <span>Success metric: {action.metric}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {plan.milestones && plan.milestones.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2">Milestones</h3>
            <div className="flex flex-wrap gap-2">
              {plan.milestones.map((ms, i) => (
                <Badge key={i} variant="outline" className="py-1 px-3">
                  <CheckCircle2 className="h-3 w-3 mr-1 text-nuru-green-600" />{ms}
                </Badge>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 bg-muted/30">
        <div className="container mx-auto px-4 py-8">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-2xl font-bold text-nuru-green-800 flex items-center gap-2">
                <FileText className="h-6 w-6" /> Career Action Plan
              </h1>
              <p className="text-muted-foreground mt-1">Your personalized 30-day, 90-day, and 1-year career roadmap</p>
            </div>
            {hasData && (
              <Button variant="outline" onClick={exportPDF}>
                <Download className="mr-2 h-4 w-4" /> Export PDF
              </Button>
            )}
          </div>

          {!hasData && !loading && (
            <Card className="text-center">
              <CardContent className="p-12">
                <FileText className="h-12 w-12 text-nuru-green-600 mx-auto mb-4" />
                <h2 className="text-xl font-bold mb-2">Generate Your Action Plan</h2>
                <p className="text-muted-foreground mb-6 max-w-md mx-auto">
                  Our AI will create a structured career action plan with specific goals, actions, and milestones for the next 30 days, 90 days, and 1 year.
                </p>
                <Button onClick={generatePlan} className="bg-nuru-green-600 hover:bg-nuru-green-700">
                  Generate Plan <FileText className="ml-2 h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
          )}

          {loading && (
            <Card className="text-center">
              <CardContent className="p-12">
                <Loader2 className="h-8 w-8 animate-spin text-nuru-green-600 mx-auto mb-4" />
                <h2 className="text-lg font-semibold">Creating your action plan...</h2>
                <p className="text-sm text-muted-foreground">Our AI is building a personalized roadmap for your career journey</p>
              </CardContent>
            </Card>
          )}

          {hasData && !loading && (
            <div ref={planRef}>
              {reasoning && (
                <Card className="mb-6">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-2 mb-1">
                      {approved ? (
                        <Badge className="bg-nuru-green-100 text-nuru-green-700"><CheckCircle2 className="h-3 w-3 mr-1" /> Guardian Approved</Badge>
                      ) : (
                        <Badge variant="destructive">Under Review</Badge>
                      )}
                    </div>
                    <p className="text-sm text-muted-foreground">{reasoning}</p>
                  </CardContent>
                </Card>
              )}

              <Tabs defaultValue="30days">
                <TabsList className="w-full">
                  <TabsTrigger value="30days" className="flex-1"><Clock className="h-4 w-4 mr-1" /> 30 Days</TabsTrigger>
                  <TabsTrigger value="90days" className="flex-1"><Clock className="h-4 w-4 mr-1" /> 90 Days</TabsTrigger>
                  <TabsTrigger value="1year" className="flex-1"><Clock className="h-4 w-4 mr-1" /> 1 Year</TabsTrigger>
                </TabsList>

                <TabsContent value="30days" className="mt-4">
                  {plan30 && (
                    <Card>
                      <CardHeader>
                        <CardTitle className="text-lg flex items-center gap-2">
                          <Badge className="bg-nuru-green-100 text-nuru-green-700">Phase 1</Badge>
                          {plan30.title || 'First 30 Days'}
                        </CardTitle>
                      </CardHeader>
                      <CardContent>{renderPlanPhase(plan30, 'green')}</CardContent>
                    </Card>
                  )}
                </TabsContent>

                <TabsContent value="90days" className="mt-4">
                  {plan90 && (
                    <Card>
                      <CardHeader>
                        <CardTitle className="text-lg flex items-center gap-2">
                          <Badge className="bg-nuru-gold-100 text-nuru-gold-700">Phase 2</Badge>
                          {plan90.title || 'First 90 Days'}
                        </CardTitle>
                      </CardHeader>
                      <CardContent>{renderPlanPhase(plan90, 'gold')}</CardContent>
                    </Card>
                  )}
                </TabsContent>

                <TabsContent value="1year" className="mt-4">
                  {plan1Year && (
                    <Card>
                      <CardHeader>
                        <CardTitle className="text-lg flex items-center gap-2">
                          <Badge className="bg-nuru-green-100 text-nuru-green-700">Phase 3</Badge>
                          {plan1Year.title || '1 Year Plan'}
                        </CardTitle>
                      </CardHeader>
                      <CardContent>{renderPlanPhase(plan1Year, 'green')}</CardContent>
                    </Card>
                  )}
                </TabsContent>
              </Tabs>

              <div className="mt-6 text-center">
                <Button variant="outline" onClick={generatePlan}>Regenerate Plan</Button>
              </div>
            </div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}
